-- Migration 06: Align an existing Supabase project with this app's expected schema
-- Safe to run multiple times.

BEGIN;

CREATE EXTENSION IF NOT EXISTS pgcrypto;


-- 1) Table name alignment: menu -> menu_items
DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM information_schema.tables
    WHERE table_schema = 'public' AND table_name = 'menu'
  )
  AND NOT EXISTS (
    SELECT 1
    FROM information_schema.tables
    WHERE table_schema = 'public' AND table_name = 'menu_items'
  ) THEN
    EXECUTE 'ALTER TABLE public.menu RENAME TO menu_items';
  END IF;
END $$;

-- 2) menu_items columns expected by app
ALTER TABLE IF EXISTS public.menu_items
  ADD COLUMN IF NOT EXISTS is_available BOOLEAN DEFAULT true,
  ADD COLUMN IF NOT EXISTS is_special BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now();

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'menu_items' AND column_name = 'available'
  )
  AND NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'menu_items' AND column_name = 'is_available'
  ) THEN
    EXECUTE 'ALTER TABLE public.menu_items RENAME COLUMN available TO is_available';
  END IF;
END $$;

-- 3) orders columns expected by app
ALTER TABLE IF EXISTS public.orders
  ADD COLUMN IF NOT EXISTS session_id TEXT,
  ADD COLUMN IF NOT EXISTS order_number BIGINT GENERATED BY DEFAULT AS IDENTITY,
  ADD COLUMN IF NOT EXISTS customer_phone TEXT,
  ADD COLUMN IF NOT EXISTS total_amount INTEGER,
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
  ADD COLUMN IF NOT EXISTS feedback_given BOOLEAN DEFAULT false;

-- Backfill customer_phone from legacy phone column
UPDATE public.orders
SET customer_phone = COALESCE(customer_phone, phone)
WHERE customer_phone IS NULL AND phone IS NOT NULL;

-- Backfill customer details from customers table when possible
UPDATE public.orders o
SET customer_name = c.name
FROM public.customers c
WHERE o.customer_id = c.id AND o.customer_name IS NULL;

UPDATE public.orders o
SET customer_phone = c.phone
FROM public.customers c
WHERE o.customer_id = c.id AND o.customer_phone IS NULL;

-- Backfill session_id for legacy rows
UPDATE public.orders
SET session_id = COALESCE(NULLIF(session_id, ''), 'legacy-' || id::text)
WHERE session_id IS NULL OR session_id = '';

ALTER TABLE IF EXISTS public.orders
  ALTER COLUMN session_id SET NOT NULL;

-- Normalize status values to app conventions
UPDATE public.orders
SET status = CASE
  WHEN status IS NULL THEN 'PLACED'
  WHEN LOWER(status) IN ('pending', 'placed') THEN 'PLACED'
  WHEN LOWER(status) = 'accepted' THEN 'ACCEPTED'
  WHEN LOWER(status) = 'preparing' THEN 'PREPARING'
  WHEN LOWER(status) = 'ready' THEN 'READY'
  WHEN LOWER(status) IN ('completed', 'done') THEN 'COMPLETED'
  WHEN LOWER(status) IN ('cancelled', 'canceled', 'rejected') THEN 'CANCELLED'
  ELSE UPPER(status)
END;

-- Backfill total_amount from order_items if missing
UPDATE public.orders o
SET total_amount = x.total_amount
FROM (
  SELECT oi.order_id, SUM(COALESCE(oi.price, 0) * COALESCE(oi.qty, 1))::INTEGER AS total_amount
  FROM public.order_items oi
  GROUP BY oi.order_id
) x
WHERE o.id = x.order_id
  AND o.total_amount IS NULL;

-- 4) order_items columns expected by app
ALTER TABLE IF EXISTS public.order_items
  ADD COLUMN IF NOT EXISTS menu_item_id UUID,
  ADD COLUMN IF NOT EXISTS quantity INTEGER,
  ADD COLUMN IF NOT EXISTS price_at_time INTEGER,
  ADD COLUMN IF NOT EXISTS item_price_at_order INTEGER;

-- Backfill order_items values from legacy columns
UPDATE public.order_items
SET quantity = COALESCE(quantity, qty, 1)
WHERE quantity IS NULL;

UPDATE public.order_items
SET price_at_time = COALESCE(price_at_time, price, 0)
WHERE price_at_time IS NULL;

UPDATE public.order_items
SET item_price_at_order = COALESCE(item_price_at_order, price_at_time, price, 0)
WHERE item_price_at_order IS NULL;

-- Add FK only if not already present
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint c
    JOIN pg_class t ON c.conrelid = t.oid
    JOIN pg_namespace n ON n.oid = t.relnamespace
    WHERE c.conname = 'order_items_menu_item_id_fkey'
      AND n.nspname = 'public'
      AND t.relname = 'order_items'
  ) THEN
    ALTER TABLE public.order_items
      ADD CONSTRAINT order_items_menu_item_id_fkey
      FOREIGN KEY (menu_item_id) REFERENCES public.menu_items(id) ON DELETE SET NULL;
  END IF;
END $$;

-- 5) Helpful indexes
CREATE INDEX IF NOT EXISTS idx_orders_session_id ON public.orders(session_id);
CREATE INDEX IF NOT EXISTS idx_orders_created_at ON public.orders(created_at);
CREATE INDEX IF NOT EXISTS idx_order_items_order_id ON public.order_items(order_id);
CREATE INDEX IF NOT EXISTS idx_menu_items_available ON public.menu_items(is_available);

-- 6) Realtime publication (if supabase_realtime exists)
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'supabase_realtime') THEN
    BEGIN
      ALTER PUBLICATION supabase_realtime ADD TABLE public.orders;
    EXCEPTION WHEN duplicate_object THEN
      NULL;
    END;

    BEGIN
      ALTER PUBLICATION supabase_realtime ADD TABLE public.menu_items;
    EXCEPTION WHEN duplicate_object THEN
      NULL;
    END;
  END IF;
END $$;

COMMIT;
